services:
  backend: 
    image: cookie-backend
    environment:
      REDIS_DNS: redis
    ports:
      - "9000:9000"

  frontend:
    image: cookie-frontend
    environment:
      BACKEND_DNS: backend
      BACKEND_PORT: "9000"
    ports:
      - "8080:8080"
    depends_on:
      - backend

  redis:
    image: redis:7.4.6
    volumes:
      - redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  redis-data:
