  apiVersion: v1                                                                                                             
  kind: Service                                                                                                              
  metadata:                                                                                                                  
    name: cookie-backend                                                                                                    
  spec:                  
    type: ClusterIP
    selector:     
      app: cookie-backend
    ports:                
      - port: 9000
        targetPort: 9000