apiVersion: apps/v1
kind: Deployment
metadata:
  name: cookie-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cookie-frontend
  template:
    metadata:
      labels:
        app: cookie-frontend
    spec:
      containers:
        - name: frontend
          image: cookie-frontend
          ports:
            - containerPort: 8080
          env:
            - name: BACKEND_DNS                                                                                                      
              value: cookie-backend                                                                                                  
            - name: BACKEND_PORT
              value: "9000"  