name: Main workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  github_username: ${{ github.actor }}
  github_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Setup:
    runs-on: ubuntu-22.04
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Go
        uses: actions/setup-go@v5
  Build:
    runs-on: ubuntu-22.04
    needs: [Setup]
    steps:
      - name: Build backend
        run: cd backend && go build
      - name: Build frontend
        run: cd frontend && go build
  Test:
    runs-on: ubuntu-22.04
    needs: [Build]
    steps:
      - name: Run tests
        run: cd frontend && go test
