name: Main workflow
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
env:
  github_username: ${{ github.actor }}
  github_password: ${{ secrets.GITHUB_TOKEN }}
  GIT_COMMIT: ${{ github.sha }}
jobs:
  Pull:
    runs-on: ubuntu-22.04
    steps:
      - name: Pull backend
        run: docker pull nb05/cookie-backend:latest
      - name: Pull frontend
        run: docker pull nb05/cookie-frontend:latest
  Test:
    runs-on: ubuntu-22.04
    needs: [Pull]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
      - name: Run tests
        run: cd frontend && go test
